
services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: ../node_modules/.bin/nodemon node app.js
    ports:
      - "80:80"
    volumes:
      - .:/opt/app
      - notused:/opt/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=80
      - FAIL_STARTUP=0
      - DELAY_STARTUP=0
      - DELAY_HEALTHCHECK=0
      - HAPPYHEALTHCHECK=1
      - ENABLE_LOGGER=1
volumes:
    notused:
