version: '2.4'

services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: ../node_modules/.bin/nodemon node app.js
    ports:
      - "80:80"
    volumes:
      - .:/opt/app
      - notused:/opt/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
    notused:
