apiVersion: apps/v1
kind: Deployment
metadata:
  name: browncoat
spec:
  replicas: 5
  selector:
    matchLabels:
      app: browncoat
  template:
    metadata:
      labels:
        app: browncoat
    spec:
      containers:
      - name: browncoat
        image: bretfisher/browncoat:v2
        env:
          - name: DELAY_STARTUP
            value: '5000' 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: main
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: browncoat
spec:
  selector:
    app: browncoat
  ports:
  - port: 80
    targetPort: main

