apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly
spec:
  replicas: 5
  selector:
    matchLabels:
      app: firefly
  template:
    metadata:
      labels:
        app: firefly
    spec:
      containers:
      - name: firefly
        image: bretfisher/browncoat:v1
        readinessProbe:
          httpGet:
            path: '/healthz'
            port: 80
          periodSeconds: 5 
          timeoutSeconds: 3 
          initialDelaySeconds: 10
          failureThreshold: 3
              
        env:
          - name: DELAY_STARTUP
            value: '5000' 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: main
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: firefly
spec:
  selector:
    app: firefly
  ports:
  - port: 80
    targetPort: main

